### ISSUE TITLE
[Errno 21]

### ISSUE THREAD

**Issue by koenhendriks** [RaymiiOrg/NoPriv#41]
Getting the following error:

```
Processing mail 10102 from xxxxxxxxx@xxxxxx with subject xxxxxx.
Traceback (most recent call last):
  File "./nopriv.py", line 886, in <module>
    backup_mails_to_html_from_local_maildir(folder)
  File "./nopriv.py", line 818, in backup_mails_to_html_from_local_maildir
    mail_has_attachment = save_mail_attachments_to_folders(mail_number, mail_for_page, folder, folder)
  File "./nopriv.py", line 703, in save_mail_attachments_to_folders
    with open(att_path, 'wb') as att_file:
IOError: [Errno 21] Is a directory: 'INBOX/2010/04/10101/attachments/'
```

Any help ?

**Comment by andrewjsi** [comment]
I have the same problem on my Debian Wheezy, Python version 2.7.3. 

```
Processing mail 94 from web@jsshayer.h...... with subject Re: G&#243;lyav&#225;r&#243; v&#225;ltoz&#225;s.
Traceback (most recent call last):
  File "./nopriv.py", line 886, in <module>
    backup_mails_to_html_from_local_maildir(folder)
  File "./nopriv.py", line 818, in backup_mails_to_html_from_local_maildir
    mail_has_attachment = save_mail_attachments_to_folders(mail_number, mail_for_page, folder, folder)
  File "./nopriv.py", line 703, in save_mail_attachments_to_folders
    with open(att_path, 'wb') as att_file:
IOError: [Errno 21] Is a directory: 'INBOX/2017/05/96/attachments/'
```
